spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: backend
  datasource:
    url: 'jdbc:postgresql://${DB_HOST:185.84.163.95}:${DB_PORT:5432}/${DB_NAME:nea}'
    username: ${DB_USERNAME:nastya}
    password: ${DB_PASSWORD:123321}
    driver-class-name: 'org.postgresql.Driver'
  jpa:
    database: 'postgresql'
    show-sql: true
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
    hibernate:
      ddl-auto: none
    open-in-view: false
    generate-ddl: false
  flyway:
    enabled: true
  mail:
    host: smtp.mail.ru
    username: snoyter@mail.ru
    password: MfU454qpp6gKDutdqx1i
    port: 465
    protocol: smtps

jwt:
  secret: test123321SSS

server:
  servlet:
    context-path: /api

upload:
  path:
    C:\Users\snoyter\Desktop\01_Projects\backend\images\

hostname: localhost

mail:
  nea: nea@mail.ru